// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UniRide.Infrastructure.Data;

#nullable disable

namespace UniRide.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518120041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            AppDbContextModelSnapshot.BuildModelForMigration(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
