// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using UniRide.Infrastructure.Data;

#nullable disable

namespace UniRide.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder) => BuildModelForMigration(modelBuilder);

        internal static void BuildModelForMigration(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniRide.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsRead").HasColumnType("bit");
                    b.Property<string>("Message").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<int>("ReceiverId").HasColumnType("int");
                    b.Property<int>("RideId").HasColumnType("int");
                    b.Property<int>("SenderId").HasColumnType("int");
                    b.Property<DateTime>("SentAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("ChatMessageId");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("RideId");
                    b.HasIndex("SenderId");
                    b.HasIndex("ReceiverId", "IsRead");
                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsRead").HasColumnType("bit");
                    b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("NotificationId");
                    b.HasIndex("UserId");
                    b.HasIndex("UserId", "IsRead");
                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("CreatedByIp").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                    b.Property<string>("ReplacedByToken").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                    b.Property<string>("RevokedByIp").HasColumnType("nvarchar(max)");
                    b.Property<string>("Token").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("RefreshTokenId");
                    b.HasIndex("Token").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("PassengerId").HasColumnType("int");
                    b.Property<int>("ReservationStatus").HasColumnType("int");
                    b.Property<int>("RideId").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("ReservationId");
                    b.HasIndex("PassengerId");
                    b.HasIndex("RideId");
                    b.HasIndex("RideId", "PassengerId", "ReservationStatus");
                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));
                    b.Property<string>("Comment").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("Rating").HasColumnType("int");
                    b.Property<int>("ReviewerId").HasColumnType("int");
                    b.Property<int>("RideId").HasColumnType("int");
                    b.Property<int>("TargetUserId").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("ReviewId");
                    b.HasIndex("ReviewerId");
                    b.HasIndex("RideId");
                    b.HasIndex("TargetUserId");
                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Ride", b =>
                {
                    b.Property<int>("RideId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RideId"));
                    b.Property<int>("AvailableSeats").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("DepartureTime").HasColumnType("datetime2");
                    b.Property<string>("Destination").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<double>("DistanceKm").HasColumnType("float");
                    b.Property<int>("DriverId").HasColumnType("int");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<string>("StartLocation").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<string>("University").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.HasKey("RideId");
                    b.HasIndex("DepartureTime");
                    b.HasIndex("DriverId");
                    b.HasIndex("Status");
                    b.HasIndex("University");
                    b.ToTable("Rides");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<int>("FailedLoginAttempts").HasColumnType("int");
                    b.Property<string>("FullName").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<bool>("IsSuspended").HasColumnType("bit");
                    b.Property<bool>("IsVerified").HasColumnType("bit");
                    b.Property<DateTime?>("LockedOutUntil").HasColumnType("datetime2");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("PhoneNumber").HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("ProfileImageUrl").HasMaxLength(512).HasColumnType("nvarchar(512)");
                    b.Property<double>("Rating").HasColumnType("float");
                    b.Property<int>("Role").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<string>("University").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("VerificationRequestedAt").HasColumnType("datetime2");
                    b.HasKey("UserId");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("PhoneNumber").IsUnique().HasFilter("[PhoneNumber] IS NOT NULL");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UniRide.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("UniRide.Domain.Entities.User", "Passenger")
                        .WithMany("Reservations")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("UniRide.Domain.Entities.Ride", "Ride")
                        .WithMany("Reservations")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Passenger");
                    b.Navigation("Ride");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Ride", b =>
                {
                    b.HasOne("UniRide.Domain.Entities.User", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.Ride", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("UniRide.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                    b.Navigation("Reservations");
                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
